language: java
addons:
  sonarcloud:
    organization: "jangchulwoon-github"
    token:
      secure: $chulwoon
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner