language: java
addons:
  sonarcloud:
    organization: "jangchulwoon-github" # the key of the org you chose at step #3
    token:
      secure: chulwoon.jang # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner