dist: trusty
sudo: required
jdk:
- oraclejdk8
addons:
  sonarcloud:
    organization: jangchulwoon-github
script:
- mvn clean install sonar:sonar
env:
  global:
    secure: PYpZy7gMPLx7dGpuUIDWA8D7jjwuhABA7N25+miqW6ypCXsFfHb0w7G79OBKx9BGDKI2SLJurBvlsefXqNSTfizKEqsgLC9BeHqRiBHfk1mw1BqhFuhtqxoBJx5DG1A9Q1VVvJrdBuJ25GMJ0JHHo/w/qEO1TT9LbK5W65BIIcj3YEUFsU87Eb3hriNDjVJNcSpEFbnWMbkKp80YYZsKLiEXzmU4yS9jvvSrN5SjRSqhl4ASNC2woPMMTj3mpfipvMVBU4ADD/OMpML9eOO5eENiJIJlE6m6VwYs55AsOK0OiL+vr4hIOqtomwHMp+i00+HVj2dw8q21LwTuPYN/5eiyaoifCAlmU9Ov03+t/4ODA+k9q1VQqxoEGob44oRQpZW4rXrxx/BRL2nsjznaDr6I2Ia2Y1nBngET0tw+U6sR6WuZwvjsMd4lt9AMhTcElcxl7+6aqKrRSXHbn9pP5TQjmkdVZF9oQRyqG5D1SFzMBgItIWJsScl9AL7TJf8rl+S4G483d6BtsRVWM87Ablk4kdhLAZWo1SPF7/qx3va4LSE5zZqeCuCI9Xx+JPS6FJBEko6UcemzcS/YOBXtTLiccUI1AxrziaW+xDE0VjdXMwDsmdiAGwibEkIO2m9kcPo+s5bukqa9jYzNb9HSF2Efougzw9ULuv8RLV/11Ik=
